// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

namespace SixtyThreeBits.Core.DB
{
    public partial class DBCoreDataContext : DbContext
    {
        public DBCoreDataContext()
        {
        }

        public DBCoreDataContext(DbContextOptions<DBCoreDataContext> options)
            : base(options)
        {
        }                

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {                        
            OnModelCreatingPartial(modelBuilder);
        }        
    }
}