// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using SixtyThreeBits.Core.DB.Tables;

namespace SixtyThreeBits.Core.DB
{
    public partial class DBCoreDataContext : DbContext
    {
        public DBCoreDataContext()
        {
        }

        public DBCoreDataContext(DbContextOptions<DBCoreDataContext> options)
            : base(options)
        {
        }                

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {                        
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}