//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixtyThreeBits.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SixtyThreeBits.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TextAdd {
            get {
                return ResourceManager.GetString("TextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        public static string TextAllDevexpressGridFilterRaw {
            get {
                return ResourceManager.GetString("TextAllDevexpressGridFilterRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this item?.
        /// </summary>
        public static string TextConfirmDelete {
            get {
                return ResourceManager.GetString("TextConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this attachment?.
        /// </summary>
        public static string TextConfirmDeleteAttachment {
            get {
                return ResourceManager.GetString("TextConfirmDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this item will also delete all child items. Do you really want to continue?.
        /// </summary>
        public static string TextConfirmDeleteRecursive {
            get {
                return ResourceManager.GetString("TextConfirmDeleteRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TextDelete {
            get {
                return ResourceManager.GetString("TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry something went wrong.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has been finished successfully.
        /// </summary>
        public static string TextSuccess {
            get {
                return ResourceManager.GetString("TextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TextUpdate {
            get {
                return ResourceManager.GetString("TextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid.
        /// </summary>
        public static string ValidationEmailFormatInvalid {
            get {
                return ResourceManager.GetString("ValidationEmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page slug is not unique.
        /// </summary>
        public static string ValidationPageSlugNotUniq {
            get {
                return ResourceManager.GetString("ValidationPageSlugNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be more then 8 symbols.
        /// </summary>
        public static string ValidationPasswordLength {
            get {
                return ResourceManager.GetString("ValidationPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current password.
        /// </summary>
        public static string ValidationPasswordOldNotMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordOldNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords not match.
        /// </summary>
        public static string ValidationPasswordsNotMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one letter and one digit.
        /// </summary>
        public static string ValidationPasswordStrength {
            get {
                return ResourceManager.GetString("ValidationPasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title is required.
        /// </summary>
        public static string ValidationRequiredPageTitle {
            get {
                return ResourceManager.GetString("ValidationRequiredPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length has been exceeded. Only {0} symbols are allowed..
        /// </summary>
        public static string ValidationTextMaxLength {
            get {
                return ResourceManager.GetString("ValidationTextMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email is already in use.
        /// </summary>
        public static string ValidationUserEmailNotUniq {
            get {
                return ResourceManager.GetString("ValidationUserEmailNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string ValidationUserInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("ValidationUserInvalidUsernameOrPassword", resourceCulture);
            }
        }
    }
}
