// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SixtyThreeBits.Core.DB.Tables
{
    public partial class Dictionaries
    {
        public Dictionaries()
        {
            InverseDictionaryParent = new HashSet<Dictionaries>();
        }

        public int DictionaryID { get; set; }
        public int? DictionaryParentID { get; set; }
        public string DictionaryCaption { get; set; }
        public string DictionaryCaptionEng { get; set; }
        public string DictionaryCaptionRus { get; set; }
        public short? DictionaryLevel { get; set; }
        public string DictionaryHierarchy { get; set; }
        public string DictionaryStringCode { get; set; }
        public int? DictionaryIntCode { get; set; }
        public decimal? DictionaryDecimalValue { get; set; }
        public int? DictionaryCode { get; set; }
        public bool DictionaryIsDefault { get; set; }
        public bool? DictionaryIsVisible { get; set; }
        public int? DictionarySortIndex { get; set; }
        public DateTime CRTime { get; set; }

        public virtual Dictionaries DictionaryParent { get; set; }
        public virtual ICollection<Dictionaries> InverseDictionaryParent { get; set; }
    }
}