// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SixtyThreeBits.Core.DB.Tables
{
    public partial class Pages
    {
        public Pages()
        {
            InversePageParent = new HashSet<Pages>();
        }

        public int PageID { get; set; }
        public int? PageParentID { get; set; }
        public string PageSlug { get; set; }
        public string PageTitle { get; set; }
        public string PageTitleEng { get; set; }
        public string PageTitleRus { get; set; }
        public string PageText { get; set; }
        public string PageTextEng { get; set; }
        public string PageTextRus { get; set; }
        public string PageData { get; set; }
        public string PageDataEng { get; set; }
        public string PageDataRus { get; set; }
        public string PageShortDescription { get; set; }
        public string PageShortDescriptionEng { get; set; }
        public string PageShortDescriptionRus { get; set; }
        public string PageImageFilename { get; set; }
        public int? PageCode { get; set; }
        public bool PageIsPublished { get; set; }
        public int? PageSortIndex { get; set; }
        public bool PageIsMenuItem { get; set; }
        public DateTime PageDateCreated { get; set; }

        public virtual Pages PageParent { get; set; }
        public virtual ICollection<Pages> InversePageParent { get; set; }
    }
}