// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SixtyThreeBits.Core.DB.Tables
{
    public partial class Permissions
    {
        public Permissions()
        {
            RolePermissions = new HashSet<RolePermissions>();
        }

        public int PermissionID { get; set; }
        public int? PermissionParentID { get; set; }
        public string PermissionCaption { get; set; }
        public string PermissionPagePath { get; set; }
        public string PermissionCodeName { get; set; }
        public string PermissionCode { get; set; }
        public bool PermissionIsMenuItem { get; set; }
        public string PermissionMenuIcon { get; set; }
        public int? PermissionSortIndex { get; set; }
        public DateTime CRTime { get; set; }

        public virtual ICollection<RolePermissions> RolePermissions { get; set; }
    }
}