// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SixtyThreeBits.Core.DB.Tables
{
    public partial class RolePermissions
    {
        public int RecordID { get; set; }
        public int RoleID { get; set; }
        public int PermissionID { get; set; }

        public virtual Permissions Permission { get; set; }
        public virtual Roles Role { get; set; }
    }
}