// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SixtyThreeBits.Core.DB.Tables
{
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserFirstname { get; set; }
        public string UserLastname { get; set; }
        public string UserFullname { get; set; }
        public int? UserRoleID { get; set; }
        public DateTime? UserBirthdate { get; set; }
        public string UserPhoneNumberMobile { get; set; }
        public string UserPersonalNumber { get; set; }
        public string UserAvatarFilename { get; set; }
        public bool UserIsActive { get; set; }
        public DateTime CRTime { get; set; }

        public virtual Roles UserRole { get; set; }
    }
}