<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="App_Data\**" />
    <Compile Remove="wwwroot\admin\html\**" />
    <Content Remove="App_Data\**" />
    <Content Remove="wwwroot\admin\html\**" />
    <EmbeddedResource Remove="App_Data\**" />
    <EmbeddedResource Remove="wwwroot\admin\html\**" />
    <None Remove="App_Data\**" />
    <None Remove="wwwroot\admin\html\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="63BITS-Libraries-DotNetStandart" Version="1.1.30" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="20.2.4" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="2.8.0" />
    <PackageReference Include="Imageflow.Net" Version="0.7.20" />
    <PackageReference Include="Imageflow.Server" Version="0.5.3" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Admin\Views\Home\Index.cshtml" />
    <None Include="Admin\Views\Pages\PagesTree.cshtml" />
    <None Include="Admin\Views\Pages\Page\PageProperties.cshtml" />
    <None Include="Admin\Views\Shared\FileTreeEditor\FileTreeEditor.cshtml" />
    <None Include="Admin\Views\Shared\FileTreeEditor\FileTreeEditorFile.cshtml" />
    <None Include="Views\Shared\FileTree\FileTree.cshtml" />
    <None Include="Views\Shared\FileTree\FileTreeFile.cshtml" />
    <None Include="Views\Shared\FileTree\FileTreeFolder.cshtml" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\demo\services_item.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\1_1.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\1_2.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\1_3.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\2_1.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\2_2.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\2_3.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\3_1.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\3_2.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\3_3.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\back.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_accordion.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_articles_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_articles_list.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_books_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_card.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_faq.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_flip_cards.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_head.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_html.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_iframe.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_1.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_2.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_3.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_4.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_text_sm.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_packages_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_pdf.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_product.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_quote.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_services.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_tabs.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_testimonials.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_text_img.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_text_img_sm.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_text_with_bg_and_img.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_timeline.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_title_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_title_text_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_title_text_title_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_uploads.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_video.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\close.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\copy.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\css.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\done.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\done_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\downloads.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\drug.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\eye.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\file.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\image.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\image_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\js.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\link.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\link_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\loader_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\nav.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\pencil.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\plus_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\remove.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\rotate.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\save.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\save_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\settings.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\settings_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\trash.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\trash_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\upload.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\video.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\video_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\js\page-builder.js" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\js\template63.js" />
    <None Include="wwwroot\plugins\jquery-appear\jquery.appear.js" />
    <None Include="wwwroot\plugins\jquery-confirm\jquery-confirm.min.js" />
    <None Include="wwwroot\plugins\jquery-nestedSortable\jquery.mjs.nestedSortable.js" />
    <None Include="wwwroot\plugins\jwplayer8\img\download.svg" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.compatibility.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.controls.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.html5.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.polyfills.html5.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.polyfills.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.flash.swf" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.vr.js" />
    <None Include="wwwroot\plugins\jwplayer8\player.js" />
    <None Include="wwwroot\plugins\jwplayer8\polyfills.intersection-observer.js" />
    <None Include="wwwroot\plugins\jwplayer8\polyfills.webvtt.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.airplay.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.cast.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.flash.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.hlsjs.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.html5.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.shaka.js" />
    <None Include="wwwroot\plugins\jwplayer8\related.js" />
    <None Include="wwwroot\plugins\jwplayer8\version-8.5.6" />
    <None Include="wwwroot\plugins\jwplayer8\vttparser.js" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SixtyThreeBits.Core\SixtyThreeBits.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\plugins\jquery-ui\" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties DismissedDevExtremeVersion="" />
    </VisualStudio>
  </ProjectExtensions>
</Project>