<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="App_Data\**" />
    <Content Remove="App_Data\**" />
    <EmbeddedResource Remove="App_Data\**" />
    <None Remove="App_Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="63BITS-Libraries-DotNetStandart" Version="1.1.11" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="19.2.5" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="2.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\js\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\plugins\devextreme\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Admin\Views\Home\Index.cshtml" />
    <None Include="Admin\Views\Shared\FileTreeEditor\FileTreeEditor.cshtml" />
    <None Include="Admin\Views\Shared\FileTreeEditor\FileTreeEditorFile.cshtml" />
    <None Include="Admin\Views\Shared\FileTreeEditor\FileTreeEditorFolder.cshtml" />
    <None Include="Views\Shared\FileTree\FileTree.cshtml" />
    <None Include="Views\Shared\FileTree\FileTreeFile.cshtml" />
    <None Include="Views\Shared\FileTree\FileTreeFolder.cshtml" />
    <None Include="wwwroot\plugins\jquery-confirm\jquery-confirm.min.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SixtyThreeBits.Core\SixtyThreeBits.Core.csproj" />
  </ItemGroup>

</Project>
