<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <UserSecretsId>920b1ae2-b527-45b0-b2d9-ed8ff53e6aae</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="App_Data\**" />
    <Compile Remove="wwwroot\admin\html\**" />
    <Content Remove="App_Data\**" />
    <Content Remove="wwwroot\admin\html\**" />
    <EmbeddedResource Remove="App_Data\**" />
    <EmbeddedResource Remove="wwwroot\admin\html\**" />
    <None Remove="App_Data\**" />
    <None Remove="wwwroot\admin\html\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="63BITS-Libraries-DotNetStandart" Version="1.2.0.8" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="22.1.5" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="2.8.6" />
    <PackageReference Include="Imageflow.Net" Version="0.8.5" />
    <PackageReference Include="Imageflow.Server" Version="0.7.7" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Admin\Views\Brands\Brands.cshtml" />
    <None Include="Admin\Views\Brands\Brand\BrandProperties.cshtml" />
    <None Include="Admin\Views\Categories\Category.cshtml" />
    <None Include="Admin\Views\Categories\CategoryProperties.cshtml" />
    <None Include="Admin\Views\Home\Index.cshtml" />
    <None Include="Admin\Views\Pages\PagesTree.cshtml" />
    <None Include="Admin\Views\Pages\Page\PageProperties.cshtml" />
    <None Include="Admin\Views\Products\Product.cshtml" />
    <None Include="Admin\Views\Products\Products.cshtml" />
    <None Include="Admin\Views\Shared\FileTreeEditor\FileTreeEditor.cshtml" />
    <None Include="Admin\Views\Shared\FileTreeEditor\FileTreeEditorFile.cshtml" />
    <None Include="Views\Shared\FileTree\FileTree.cshtml" />
    <None Include="Views\Shared\FileTree\FileTreeFile.cshtml" />
    <None Include="Views\Shared\FileTree\FileTreeFolder.cshtml" />
    <None Include="wwwroot\admin\js\Brands\BrandItem.js" />
    <None Include="wwwroot\admin\js\Brands\Brands.js" />
    <None Include="wwwroot\admin\js\Categories\Category\CategoriesItem.js" />
    <None Include="wwwroot\admin\js\Products\Product.js" />
    <None Include="wwwroot\admin\js\Products\Products.js" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\demo\services_item.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\1_1.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\1_2.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\1_3.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\2_1.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\2_2.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\2_3.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\3_1.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\3_2.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\alignment\3_3.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\arrow_right_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\back.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_accordion.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_articles_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_articles_list.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_books_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_cards_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_card_2col.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_flip_cards.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_form.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_form_signup.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_head.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_html.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_iframe.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_img_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_media_object.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_media_objects_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_packages_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_pdf.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_people_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_post_cards_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_quote.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_services.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_slide.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_slider.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_tabs.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_testimonials.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_text_img.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_text_img_sm.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_text_with_bg_and_img.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_title_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_title_text_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_title_text_title_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_uploads.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_video.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_video_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_video_jwp.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_video_jwp_grid.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\builder\bl_video_text.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\chevron.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\close.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\copy.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\css.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\done.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\done_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\downloads.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\drug.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\eye.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\file.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\image.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\image_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\js.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\link.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\link_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\loader_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\nav.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\pencil.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\plus.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\plus_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\remove.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\rotate.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\save.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\save_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\settings.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\settings_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\trash.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\trash_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\upload.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\video.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\images\icons\video_white.svg" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\js\page-builder.js" />
    <None Include="wwwroot\plugins\63bits-pageBuilder\js\template63.js" />
    <None Include="wwwroot\plugins\dropzone\dropzone.min.js" />
    <None Include="wwwroot\plugins\jquery-appear\jquery.appear.js" />
    <None Include="wwwroot\plugins\jquery-confirm\jquery-confirm.min.js" />
    <None Include="wwwroot\plugins\jquery-masked-input\jquery.maskedinput.min.js" />
    <None Include="wwwroot\plugins\jquery-nestedSortable\jquery.mjs.nestedSortable.js" />
    <None Include="wwwroot\plugins\jwplayer8\img\download.svg" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.compatibility.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.controls.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.html5.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.polyfills.html5.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.controls.polyfills.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.core.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.flash.swf" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.js" />
    <None Include="wwwroot\plugins\jwplayer8\jwplayer.vr.js" />
    <None Include="wwwroot\plugins\jwplayer8\player.js" />
    <None Include="wwwroot\plugins\jwplayer8\polyfills.intersection-observer.js" />
    <None Include="wwwroot\plugins\jwplayer8\polyfills.webvtt.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.airplay.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.cast.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.flash.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.hlsjs.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.html5.js" />
    <None Include="wwwroot\plugins\jwplayer8\provider.shaka.js" />
    <None Include="wwwroot\plugins\jwplayer8\related.js" />
    <None Include="wwwroot\plugins\jwplayer8\version-8.5.6" />
    <None Include="wwwroot\plugins\jwplayer8\vttparser.js" />
    <None Include="wwwroot\plugins\malihu-scrollbar\jquery.mCustomScrollbar.concat.min.js" />
    <None Include="wwwroot\plugins\malihu-scrollbar\jquery.mCustomScrollbar.js" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78-RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78ms-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\78ms-RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\83pv-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\90ms-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\90ms-RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\90msp-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\90msp-RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\90pv-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\90pv-RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Add-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Add-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Add-RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Add-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-0.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-1.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-3.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-4.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-5.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-6.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-CNS1-UCS2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-GB1-0.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-GB1-1.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-GB1-2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-GB1-3.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-GB1-4.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-GB1-5.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-GB1-UCS2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-0.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-1.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-3.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-4.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-5.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-6.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Japan1-UCS2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Korea1-0.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Korea1-1.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Korea1-2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Adobe-Korea1-UCS2.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\B5pc-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\B5pc-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\CNS-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\CNS-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\CNS1-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\CNS1-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\CNS2-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\CNS2-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\ETen-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\ETen-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\ETenms-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\ETenms-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\ETHK-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\ETHK-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Ext-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Ext-RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Ext-RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Ext-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GB-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GB-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GB-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GB-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBK-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBK-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBK2K-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBK2K-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBKp-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBKp-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBpc-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBpc-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBT-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBT-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBT-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBT-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBTpc-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\GBTpc-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Hankaku.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Hiragana.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKdla-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKdla-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKdlb-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKdlb-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKgccs-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKgccs-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKm314-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKm314-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKm471-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKm471-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKscs-B5-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\HKscs-B5-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Katakana.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSC-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSC-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSC-Johab-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSC-Johab-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSCms-UHC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSCms-UHC-HW-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSCms-UHC-HW-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSCms-UHC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSCpc-EUC-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\KSCpc-EUC-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\LICENSE" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\NWP-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\NWP-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\RKSJ-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\RKSJ-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\Roman.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UCS2-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UCS2-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UTF16-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UTF16-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UTF32-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UTF32-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UTF8-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniCNS-UTF8-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UCS2-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UCS2-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UTF16-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UTF16-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UTF32-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UTF32-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UTF8-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniGB-UTF8-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UCS2-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UCS2-HW-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UCS2-HW-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UCS2-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UTF16-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UTF16-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UTF32-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UTF32-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UTF8-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS-UTF8-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS2004-UTF16-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS2004-UTF16-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS2004-UTF32-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS2004-UTF32-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS2004-UTF8-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJIS2004-UTF8-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJISPro-UCS2-HW-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJISPro-UCS2-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJISPro-UTF8-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJISX0213-UTF32-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJISX0213-UTF32-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJISX02132004-UTF32-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniJISX02132004-UTF32-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UCS2-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UCS2-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UTF16-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UTF16-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UTF32-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UTF32-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UTF8-H.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\UniKS-UTF8-V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\V.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\cmaps\WP-Symbol.bcmap" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-check.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-comment.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-help.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-insert.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-key.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-newparagraph.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-noicon.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-note.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\annotation-paragraph.svg" />
    <None Include="wwwroot\plugins\pdfjs\images\grab.cur" />
    <None Include="wwwroot\plugins\pdfjs\images\grabbing.cur" />
    <None Include="wwwroot\plugins\pdfjs\js\pdf.js" />
    <None Include="wwwroot\plugins\pdfjs\js\pdf.js.map" />
    <None Include="wwwroot\plugins\pdfjs\js\pdf.worker.js" />
    <None Include="wwwroot\plugins\pdfjs\js\pdf.worker.js.map" />
    <None Include="wwwroot\plugins\pdfjs\js\viewer.js" />
    <None Include="wwwroot\plugins\pdfjs\js\viewer.js.map" />
    <None Include="wwwroot\plugins\pdfjs\locale\ach\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\af\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\an\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ar\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ast\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\az\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\be\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\bg\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\bn\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\bo\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\brx\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\br\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\bs\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\cak\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ca\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\cs\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\cy\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\da\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\de\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\dsb\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\el\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\en-CA\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\en-GB\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\en-US\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\eo\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\es-AR\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\es-CL\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\es-ES\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\es-MX\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\et\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\eu\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\fa\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ff\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\fi\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\fr\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\fy-NL\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ga-IE\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\gd\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\gl\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\gn\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\gu-IN\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\he\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\hi-IN\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\hr\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\hsb\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\hu\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\hy-AM\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\hye\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ia\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\id\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\is\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\it\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ja\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\kab\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ka\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\kk\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\km\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\kn\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ko\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\lij\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\locale.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\lo\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ltg\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\lt\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\lv\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\meh\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\mk\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\mr\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ms\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\my\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\nb-NO\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ne-NP\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\nl\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\nn-NO\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\oc\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\pa-IN\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\pl\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\pt-BR\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\pt-PT\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\rm\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ro\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ru\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\scn\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\si\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\sk\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\sl\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\son\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\sq\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\sr\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\sv-SE\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ta\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\te\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\th\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\tl\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\trs\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\tr\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\uk\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\ur\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\uz\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\vi\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\wo\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\xh\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\zh-CN\viewer.properties" />
    <None Include="wwwroot\plugins\pdfjs\locale\zh-TW\viewer.properties" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SixtyThreeBits.Core\SixtyThreeBits.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\plugins\jquery-ui\" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties DismissedDevExtremeVersion="" />
    </VisualStudio>
  </ProjectExtensions>
</Project>